name: Deployment

on: workflow_dispatch

jobs:
  integrationtesting:
    runs-on: ubuntu-latest  
    steps:
      - name: Running Compile checks
        run: |
          echo "Compile Completed"
      - name: Running Integration Test Suite 102
        run: |
          echo "Integration Test Suite 102: PASS"
      - name: Running Integration Test Suite 101
        run: |
         echo "Integration Test Suite 101: PASS"  
  regressiontesting:
    runs-on: ubuntu-latest 
    needs: integrationtesting
    steps:
      - name: Running Regression Test Cases
        run: |
          echo "All Regression Test Cases have PASSED"
  codecoverage:
    runs-on: ubuntu-latest
    needs: integrationtesting
    steps:
      - name: Code Coverage
        run: |
          echo "Code coverage 85%"
  securitytesting:
    runs-on: ubuntu-latest
    needs: integrationtesting
    steps:
      - name: Security Checks
        run: |
          echo "No Security issues found!"
  deployment:
    runs-on: ubuntu-latest
    needs: [regressiontesting, codecoverage, securitytesting]
    environment: prod-env
    steps:
      - name: deploy
        run: |
          echo "Deploy Completed"
